
package delivery.server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://service.server.delivery/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.server.delivery/", className = "delivery.server.service.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.server.delivery/", className = "delivery.server.service.HelloResponse")
    @Action(input = "http://service.server.delivery/Server/helloRequest", output = "http://service.server.delivery/Server/helloResponse")
    public void hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
