
package delivery.sender.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Sender", targetNamespace = "http://service.sender.delivery/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sender {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "post", targetNamespace = "http://service.sender.delivery/", className = "delivery.sender.service.Post")
    @ResponseWrapper(localName = "postResponse", targetNamespace = "http://service.sender.delivery/", className = "delivery.sender.service.PostResponse")
    @Action(input = "http://service.sender.delivery/Sender/postRequest", output = "http://service.sender.delivery/Sender/postResponse")
    public void post(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
