
package delivery.sender.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SenderService", targetNamespace = "http://service.sender.delivery/", wsdlLocation = "file:/media/juan/DATA/linux/sistemas-distribuidos/delivery-safeguard/client/src/main/java/sender.wsdl")
public class SenderService
    extends Service
{

    private final static URL SENDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDERSERVICE_EXCEPTION;
    private final static QName SENDERSERVICE_QNAME = new QName("http://service.sender.delivery/", "SenderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/media/juan/DATA/linux/sistemas-distribuidos/delivery-safeguard/client/src/main/java/sender.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDERSERVICE_WSDL_LOCATION = url;
        SENDERSERVICE_EXCEPTION = e;
    }

    public SenderService() {
        super(__getWsdlLocation(), SENDERSERVICE_QNAME);
    }

    public SenderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDERSERVICE_QNAME, features);
    }

    public SenderService(URL wsdlLocation) {
        super(wsdlLocation, SENDERSERVICE_QNAME);
    }

    public SenderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDERSERVICE_QNAME, features);
    }

    public SenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SenderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Sender
     */
    @WebEndpoint(name = "SenderImplPort")
    public Sender getSenderImplPort() {
        return super.getPort(new QName("http://service.sender.delivery/", "SenderImplPort"), Sender.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Sender
     */
    @WebEndpoint(name = "SenderImplPort")
    public Sender getSenderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sender.delivery/", "SenderImplPort"), Sender.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDERSERVICE_EXCEPTION!= null) {
            throw SENDERSERVICE_EXCEPTION;
        }
        return SENDERSERVICE_WSDL_LOCATION;
    }

}
